---
- name: Security Configuration
  hosts: webservers
  become: true

  tasks:

    - name: Install UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH
      ufw:
        rule: allow
        port: "22"

    - name: Enable Firewall
      ufw:
        state: enabled