---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"

- name: Enable UFW
  ufw:
    state: enabled

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Allow Grafana
  ufw:
    rule: allow
    port: "3000"

- name: Allow Prometheus
  ufw:
    rule: allow
    port: "9090"

- name: Allow Uptime Kuma
  ufw:
    rule: allow
    port: "3001"

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"